### ISSUE TITLE
Add an open source license

### ISSUE THREAD

**Issue by TheButlah** [alecjprobst/SlimeVRMotherboard#1]
I suggest adding a CERN-OHL-**P** v2 license - it is a permissive license like MIT, but it better applies to hardware. You can see [my repo](https://github.com/TheButlah/slimevr_pcb) for reference

**Comment by alecjprobst** [comment]
Good suggestion, added. Thanks!

**Comment by TheButlah** [comment]
You added the **S** variant of the license - was this intentional? This would require anyone making derivative work to force their code to be open source and licensed under the same license (much like GPLv3).

Would you consider relicensing under the **P** variant?

**Comment by alecjprobst** [comment]
Woops, I meant to do a permissive type. My bad, thanks for checking!
