### ISSUE TITLE
Suggestion for plugs

### ISSUE THREAD

**Issue by Sacred-Shadow** [alecjprobst/SlimeVRMotherboard#2]
Thank you for the excellent guide and the really good motherboard. 👍🏻

One thing I have is, could you possibly offer the motherboard in a version where a JST connector fits? 
Especially for the IMU connection, that would be great. Currently, it doesn't fit due to the hole spacing.

**Comment by alecjprobst** [comment]
I'm afraid I don't have time to do this currently, the KiCAD files should allow you to make that change very easily though. The JST connector may not fit inside of the case however.
